# Generated by Django 5.1.7 on 2025-03-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.DecimalField(decimal_places=5, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('net', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('notes', models.CharField(default='', max_length=50)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
            ],
        ),
    ]
