# Generated by Django 5.1.7 on 2025-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_beautycategory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BeautyCategory',
        ),
    ]
