# Generated by Django 5.1.7 on 2025-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_beautyproduct_delete_beautycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beauty_images/'),
        ),
    ]
