# Generated by Django 5.1.7 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_beautyproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyproduct',
            name='color',
            field=models.CharField(max_length=50, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beauty_images/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='notes',
            field=models.CharField(default='', max_length=50, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='qty',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='tax',
            field=models.FloatField(verbose_name='الضريبة'),
        ),
        migrations.AlterField(
            model_name='beautyproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي'),
        ),
    ]
