# Generated by Django 4.2.20 on 2025-03-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_alter_product_price_alter_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
